### ISSUE TITLE
merge on last version is somewhat broken

### ISSUE THREAD

**Issue by eduardogarcia234** [vilmire/neptune-osk#2]
hi... i wanna change and add some features on your githubs source but your merge dev to main branch was broken... the code was broken at overlay.cs 
  I tried to make corrections, but when running the program crashes. Could you update or check  on it?

thank you

**Comment by vilmire** [comment]
merge conflict sorry, changed default branch to dev2.

should some change in Osklib.csproj
<TargetFrameworks>netstandard2.0</TargetFrameworks> 
and remove <Import Project="$(SolutionDir)osklib.targets" />
